<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Number 1 is not a number</name>
   <tag></tag>
   <elementGuidId>05650e9c-444d-407f-9300-674496e08fbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#errorMsgField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='errorMsgField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5ba10bf7-da61-4efc-bd8a-75a0d6d1166a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>errorMsgField</value>
      <webElementGuid>55b8bb52-80ba-4b00-a52c-a798bb09cd01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Number 1 is not a number</value>
      <webElementGuid>094aabae-4d40-4266-ab7d-2411c3ea5c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;errorMsgField&quot;)</value>
      <webElementGuid>2aa591f6-d8d8-470e-b412-46b84c9e34b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='errorMsgField']</value>
      <webElementGuid>35dad649-a0fc-4eb5-820c-60dee5a61cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='errorForm']/h3/font/i/label</value>
      <webElementGuid>6acb00ec-0843-4e98-9a97-e2b9da14bb0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build'])[1]/following::label[1]</value>
      <webElementGuid>15054a91-0ca5-4013-9482-2527edfa69eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prototype'])[1]/following::label[2]</value>
      <webElementGuid>072bf613-e50b-479f-b83a-bb2286c55d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate'])[1]/preceding::label[1]</value>
      <webElementGuid>4d3aa7a8-c3b5-46a5-9cfd-53eba6830362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First number'])[1]/preceding::label[1]</value>
      <webElementGuid>f62b11b9-1c9b-49a5-9fb5-d4a83075bbba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Number 1 is not a number']/parent::*</value>
      <webElementGuid>549783bd-e0d4-4234-bd49-b41077741043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i/label</value>
      <webElementGuid>047657b9-b49a-422b-8e2b-d9ceb42d9ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'errorMsgField' and (text() = 'Number 1 is not a number' or . = 'Number 1 is not a number')]</value>
      <webElementGuid>228d4cee-cefe-4539-8dce-ba4e78e551a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
