<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Prototype                          1_8a1659</name>
   <tag></tag>
   <elementGuidId>6059d71d-a138-4b7e-bfb9-e3a8f2d9b8eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectBuild</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectBuild']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>60e05897-c5e1-42d0-b4cd-1da5e8dff1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>element select medium</value>
      <webElementGuid>f82eb2ef-af83-4e89-a7c5-86524853d88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectBuild</value>
      <webElementGuid>6e6276f5-1283-4d0d-8168-4fe7ea32a889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectBuild</value>
      <webElementGuid>e53af920-4659-4fb3-baad-efb6c0b4a0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>buildChanged(this.preset)</value>
      <webElementGuid>eee6231c-63fa-4a74-9239-dd2660e6bd56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                          Prototype
                          1
                          2
                          3
                          4
                          5
                          6
                          7
                          8
                          9
                      </value>
      <webElementGuid>6c1fafb9-6a86-4f78-a27a-9b88f6b9ae7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectBuild&quot;)</value>
      <webElementGuid>043bc915-a6a3-4ebc-9aa1-2bd12b1c6dca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectBuild']</value>
      <webElementGuid>506eb8ee-56c3-4ce8-843c-ccb54178a0e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-body']/div/div/div/div/div[2]/select</value>
      <webElementGuid>1ea907a1-7966-4eb9-9cbc-789549f607bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build'])[1]/following::select[1]</value>
      <webElementGuid>27671d7a-efcd-4ec0-8a4e-93f5275973db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prototype'])[1]/following::select[1]</value>
      <webElementGuid>4c494a45-386b-4328-ae99-9fd1346b0a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate'])[1]/preceding::select[1]</value>
      <webElementGuid>e19567df-aeac-4b01-bd18-27a5e497164a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First number'])[1]/preceding::select[1]</value>
      <webElementGuid>f5f31c72-d2e5-407c-978c-f48aaad0e93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>5db60a43-af9e-42ed-9553-834ac2c742f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selectBuild' and @name = 'selectBuild' and (text() = ' 
                          Prototype
                          1
                          2
                          3
                          4
                          5
                          6
                          7
                          8
                          9
                      ' or . = ' 
                          Prototype
                          1
                          2
                          3
                          4
                          5
                          6
                          7
                          8
                          9
                      ')]</value>
      <webElementGuid>d280660b-6e2f-44f2-a2e6-7b8584a852d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
