<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Add                            Subtr_963217</name>
   <tag></tag>
   <elementGuidId>c047a0cc-f182-4c5c-897d-61892d5b27fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectOperationDropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectOperationDropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0c831ead-390b-4c18-bda8-29e6066cf33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>element select medium</value>
      <webElementGuid>5f7e71b2-5e90-4f4d-9200-119108f72acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectOperationDropdown</value>
      <webElementGuid>6226a30b-9db4-4ef8-b3d4-3857373f92ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectOperation</value>
      <webElementGuid>b058b13f-c022-4a28-8e5f-5c7268484246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>operationChanged(this.preset)</value>
      <webElementGuid>4b025c2b-d4ee-4b93-8ef9-f05c737fff8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                            Add
                            Subtract
                            Multiply
                            Divide
                            Concatenate
                        </value>
      <webElementGuid>73c716f3-0ab3-4e19-8c76-42993ce639db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectOperationDropdown&quot;)</value>
      <webElementGuid>274d091c-f934-4ecf-9399-c04bb9b4db39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectOperationDropdown']</value>
      <webElementGuid>7f74dc1a-ff2e-4984-97d8-ff42dd430225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calcForm']/div[3]/div[2]/select</value>
      <webElementGuid>6da45e7b-5b88-44e9-9f19-7490f78ef042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operation'])[1]/following::select[1]</value>
      <webElementGuid>c76073c4-ea11-490e-931b-402446514293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Second number'])[1]/following::select[1]</value>
      <webElementGuid>d7d059a3-4144-406f-8e74-76a5eff063a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculating ...'])[1]/preceding::select[1]</value>
      <webElementGuid>d8e379ec-f054-4c05-8a1a-b0004397ac9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Answer'])[1]/preceding::select[1]</value>
      <webElementGuid>036736b6-52eb-4da0-8f3f-3f2d40705a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>ef2cceab-b8f4-4057-a378-dc2f6c55f876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selectOperationDropdown' and @name = 'selectOperation' and (text() = ' 
                            Add
                            Subtract
                            Multiply
                            Divide
                            Concatenate
                        ' or . = ' 
                            Add
                            Subtract
                            Multiply
                            Divide
                            Concatenate
                        ')]</value>
      <webElementGuid>0f6fa666-85e4-413f-824c-997d7fc315b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
